# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types:
          - zsh
          - bash
          - json
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: sort imports (isort)
        args: [--settings, pyproject.toml, --filter-files]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: format code (black)
  - repo: https://github.com/myint/docformatter
    rev: v1.5.0-rc1
    hooks:
      - id: docformatter
        name: format docstrings (docformatter)
        args: [--in-place, --wrap-summaries, "120", --wrap-description, "88"]
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: lint code (flake8)
        additional_dependencies: ["pep8-naming"]
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #     - id: pydocstyle
  #       name: lint docstrings (pydocstyle)
  #       additional_dependencies:
  #         - toml
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.3
    hooks:
      - id: gitlab-ci-linter
        name: lint ci pipeline config (gitlab-ci-linter)
        entry: env GITLAB_PRIVATE_TOKEN=w8i5Q1CaEpF57cqxezvG gitlab-ci-linter
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.1
    hooks:
      - id: markdownlint-cli2
        name: lint markdown files (markdownlint-cli2)
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.6.0
    hooks:
      - id: cspell
        name: check spelling (cspell)
        args:
          [--show-suggestions, --show-context, --no-must-find-files, --config, .vscode/cspell.json]
  - repo: local
    hooks:
      - id: pytest
        name: Executing tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
